# Alembic Configuration File
# the output encoding used when revision files
# are written from script.py.mako
# this sample config assumes you're starting
# fresh and you will put the migrations in the
# 'alembic' folder as a new git branch

[alembic]

# path to migration files
script_location = alembic

# template used to generate migration file names
file_template = %%(rev)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present
# defaults to the current directory
prepended_sys_path = .

# timezone to use when rendering the date
# within the migration file as well as the filename.
# string value is passed to zoneinfo.ZoneInfo()
# leave blank for localtime
# timezone =

# max length of characters to apply to the
# "slug" field on when generating a new migration
# set to 0 to disable
# truncate_slug_length = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow .pyc and .pyo files without
# a source .py file to be detected as revisions in the
# versions/ directory
# sourceless = false

# set to 'true' to detect each time init or rev is called
# whether only one head is present in the version tree
# before updating refs in alembic.ini, thus the new head would
# not be ontstoken if there are multiple heads.
# on_version_conflict = fail

# allows to include the description of change (if one was passed
# to the `revision` command) within the revision file
# new_revision_context.description

sqlalchemy.url = 

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
